### ISSUE TITLE
Appears to be dead now?

### ISSUE THREAD

**Issue by triggerx** [frankdice/tappecue-api#6]
So sad... loved having this API! :(

**Comment by frankdice** [comment]
It's always DNS. 

I was moving some things behind the scenes (Cloudflare in front, resizing the underlying VM, tidying up a bit, moving DNS servers...). Missed something, and my testing obviously cached the DNS locally so I didn't notice it (also found a monitoring bug that I need to address next week, as well as an nginx config issue).

Should be back up in the next few minutes.
